version: "3"

services:
    app:
        entrypoint: [bin/start]
        image: thanhtt/hmt_gl:latest
        container_name: greenlight-v2
        env_file: .env
        restart: unless-stopped
        ports:
            - 5000:80
        # When using external logging
        #    logging:
        #      driver: $LOG_DRIVER
        #      options:
        #        syslog-address: $LOG_ADDRESS
        #        tag: $LOG_TAG
        volumes:
            - ./log:/usr/src/app/log
            - ./storage:/usr/src/app/storage
        # When using sqlite3 as the database
        #      - ./db/production:/usr/src/app/db/production
        # When using postgresql as the database
        networks:
            - hmt
    db:
        image: postgres:9.5
        restart: unless-stopped
        ports:
            - 5433:5432
        #volumes:
        #    - ./db/production:/var/lib/postgresql/data
        environment:
            environment:
            POSTGRES_DB: greenlight_dev
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            PGDATA: /data/postgres
        networks:
            - hmt
networks:
    hmt: